apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: christiancuri-backend-nodejs
  name: christiancuri-backend-nodejs
  namespace: default
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 30
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: christiancuri-backend-nodejs
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: christiancuri-backend-nodejs
    spec:
      containers:
        - env:
            - name: ENVIRONMENT
              value: PRODUCTION
            - name: PORT
              value: "8080"
          image: christiancury/christiancuri-backend-nodejs:latest
          name: christiancuri-backend-nodejs
          ports:
            - containerPort: 8080
              protocol: "TCP"
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
              ephemeral-storage: "5Gi"
            requests:
              cpu: "1"
              memory: "500Mi"
              ephemeral-storage: "1Gi"
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: dockerhub
